### ISSUE TITLE
Audio

### ISSUE THREAD

**Issue by dmackerman** [ModusCreateOrg/DiscoverMusic#2]
- Audio needs the ability to be _paused_.
- The controls need to change from a "play" to a "pause" button once an audio has started playing. 
- **Duration** should be available if this is possible to get from the NPR API. If not, not a deal breaker.

**Comment by ecris87** [comment]
Thank you for filing this issue! :heart: 

We no longer maintain this repository, but we continue to work on the most cutting-edge open source projects. You can find amazing solutions and ideas on the [Modus Labs](https://labs.moduscreate.com?utm_source=github&utm_medium=issues&utm_campaign=deprecated) website.
