### ISSUE TITLE
Geolocation / Station Donation

### ISSUE THREAD

**Issue by dmackerman** [ModusCreateOrg/DiscoverMusic#4]
NPR does not have a centralized donation center, so the "donation panel" in the landscape view will have to be reworked. Based on the information we can get from NPR, ideally we would have Geolocation determine the closest available stations and redirect you to their donation page.

**Comment by ecris87** [comment]
Thank you for filing this issue! :heart: 

We no longer maintain this repository, but we continue to work on the most cutting-edge open source projects. You can find amazing solutions and ideas on the [Modus Labs](https://labs.moduscreate.com?utm_source=github&utm_medium=issues&utm_campaign=deprecated) website.
