### ISSUE TITLE
Favorites Page

### ISSUE THREAD

**Issue by dmackerman** [ModusCreateOrg/DiscoverMusic#6]
This is page where all of the favorites live. This should look just like the mockups, with stories appearing in a grid. There is an **Edit** button present which allows the user to delete stories from their favorites.

**Comment by ecris87** [comment]
Thank you for filing this issue! :heart: 

We no longer maintain this repository, but we continue to work on the most cutting-edge open source projects. You can find amazing solutions and ideas on the [Modus Labs](https://labs.moduscreate.com?utm_source=github&utm_medium=issues&utm_campaign=deprecated) website.
